# If not running interactively, don't do anything
case $- in
*i*) ;;
*) return ;;
esac

# append to the history file, don't overwrite it
shopt -s histappend

# bash environment variables
HISTSIZE=1000
HISTFILESIZE=2000
PROMPT_DIRTRIM=2

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# load aliases, functions
if [ -f ~/.bash_aliases ]; then
  . "/home/user/.bash_aliases"
fi

# load rust environment
if [ -f "$HOME/.cargo/env" ]; then
  . "$HOME/.cargo/env"
fi

# nvim path
PATH="/opt/nvim-linux-x86_64/bin:$PATH"

# vcpkg path
VCPKG_ROOT="$HOME/.vcpkg"
PATH=$VCPKG_ROOT:$PATH

# set shell prompt
PS1="${debian_chroot:+($debian_chroot)}\u@\h:\w\n -> "

